# Generated by Django 5.1.2 on 2024-11-02 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scolarapp', '0002_timetablesession_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routestation',
            name='route',
        ),
        migrations.RemoveField(
            model_name='routestation',
            name='station',
        ),
        migrations.RemoveField(
            model_name='transport',
            name='driver',
        ),
        migrations.DeleteModel(
            name='Route',
        ),
        migrations.DeleteModel(
            name='RouteStation',
        ),
        migrations.DeleteModel(
            name='TransportStation',
        ),
        migrations.DeleteModel(
            name='Transport',
        ),
    ]
