# Generated by Django 5.1.2 on 2025-01-27 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolarapp', '0003_alter_timetablesession_classroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='remark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
