# Generated by Django 5.1.2 on 2024-11-02 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolarapp', '0003_remove_routestation_route_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('coefficient', models.DecimalField(decimal_places=2, max_digits=4)),
                ('education_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scolarapp.educationlevel')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scolarapp.school')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scolarapp.subject')),
                ('teacher', models.ForeignKey(limit_choices_to={'role__name': 'Enseignant'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
