# Generated by Django 5.1.2 on 2025-01-27 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolarapp', '0004_user_remark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='payment_frequency',
        ),
        migrations.AddField(
            model_name='user',
            name='parent',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__name': 'Parent'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to=settings.AUTH_USER_MODEL),
        ),
    ]
