# Generated by Django 5.1.2 on 2024-11-02 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolarapp', '0005_alter_course_id_coursefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursefile',
            name='file_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
