# Generated by Django 5.1.2 on 2025-01-29 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolarapp', '0006_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='roles',
            field=models.ManyToManyField(related_name='notices', to='scolarapp.role'),
        ),
    ]
