# Generated by Django 5.1.2 on 2024-11-04 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scolarapp', '0006_coursefile_file_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='coefficient',
        ),
    ]
