# Generated by Django 5.1.2 on 2025-02-04 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scolarapp', '0007_notice_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='next_payment_date',
        ),
    ]
