# Generated by Django 5.1.2 on 2024-11-04 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolarapp', '0007_remove_course_coefficient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('coefficient', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('evaluation_date', models.DateField()),
                ('comments', models.TextField(blank=True, null=True)),
                ('student', models.ForeignKey(limit_choices_to={'role__name': 'Étudiant'}, on_delete=django.db.models.deletion.CASCADE, related_name='grades', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='scolarapp.subject')),
            ],
            options={
                'unique_together': {('student', 'subject', 'evaluation_date')},
            },
        ),
    ]
