# Generated by Django 5.1.2 on 2024-11-04 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scolarapp', '0008_grade'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='grade',
            name='evaluation_date',
        ),
    ]
