# Generated by Django 5.1.2 on 2025-02-22 22:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolarapp', '0009_homeworkbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworkbook',
            name='education_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_books', to='scolarapp.educationlevel'),
        ),
        migrations.AlterField(
            model_name='homeworkbook',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'role': 'Enseignant'}, on_delete=django.db.models.deletion.CASCADE, related_name='homework_books', to=settings.AUTH_USER_MODEL),
        ),
    ]
