# Generated by Django 5.1.2 on 2024-11-04 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolarapp', '0009_alter_grade_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='scolarapp.school'),
            preserve_default=False,
        ),
    ]
