# Generated by Django 5.1.2 on 2025-02-22 22:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolarapp', '0010_alter_homeworkbook_education_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworkbook',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'role__name': 'Enseignant'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
