# Generated by Django 5.1.2 on 2024-11-04 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolarapp', '0010_grade_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='education_level',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='scolarapp.educationlevel'),
        ),
    ]
