# Generated by Django 5.1.2 on 2024-11-04 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolarapp', '0011_grade_education_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='education_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scolarapp.educationlevel'),
        ),
    ]
