# Generated by Django 5.1.2 on 2025-02-25 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolarapp', '0011_alter_homeworkbook_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='sms_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
