# Generated by Django 5.1.2 on 2025-03-06 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolarapp', '0013_driverlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverlocation',
            name='device_id',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
