# Generated by Django 5.1.2 on 2025-03-13 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolarapp', '0014_driverlocation_device_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworkbook',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='homework_books', to='scolarapp.subject'),
            preserve_default=False,
        ),
    ]
