# Generated by Django 5.1.2 on 2024-11-05 22:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolarapp', '0015_transport_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transport',
            name='student',
        ),
        migrations.AddField(
            model_name='transport',
            name='students',
            field=models.ManyToManyField(limit_choices_to={'role__name': 'Étudiant'}, related_name='student_transports', to=settings.AUTH_USER_MODEL),
        ),
    ]
