# Generated by Django 5.1.2 on 2024-11-11 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolarapp', '0018_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='scolarapp.school'),
            preserve_default=False,
        ),
    ]
