# Generated by Django 5.1.2 on 2024-11-15 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolarapp', '0021_rename_salary_user_monthly_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='next_payment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
