# Generated by Django 5.1.2 on 2024-11-16 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolarapp', '0022_user_next_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='monthly_payment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
