# Generated by Django 5.1.2 on 2024-11-19 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scolarapp', '0025_user_parent_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='parent_key',
        ),
    ]
