# Generated by Django 5.1.2 on 2024-11-25 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolarapp', '0029_school_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='absences_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
