# Generated by Django 5.1.2 on 2024-11-25 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolarapp', '0030_alter_user_absences_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_number', models.PositiveIntegerField()),
                ('control_type', models.CharField(max_length=100)),
                ('coefficient', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('education_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controls', to='scolarapp.educationlevel')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controls', to='scolarapp.school')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controls', to='scolarapp.subject')),
                ('teacher', models.ForeignKey(limit_choices_to={'role__name': 'Enseignant'}, on_delete=django.db.models.deletion.CASCADE, related_name='controls', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
