# Generated by Django 5.1.2 on 2024-11-26 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolarapp', '0032_remove_grade_coefficient_remove_grade_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='control',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scolarapp.control'),
        ),
    ]
