# Generated by Django 5.1.2 on 2024-12-07 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolarapp', '0038_school_address_school_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='semestre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
