# Generated by Django 5.1.2 on 2024-12-08 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolarapp', '0039_school_semestre'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='code_massar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
