# Generated by Django 5.1.2 on 2024-12-08 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scolarapp', '0040_user_code_massar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='code_massar',
        ),
    ]
