# Generated by Django 5.1.2 on 2025-01-06 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolarapp', '0049_alter_user_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='education_level',
        ),
        migrations.AddField(
            model_name='user',
            name='education_levels',
            field=models.ManyToManyField(blank=True, to='scolarapp.educationlevel'),
        ),
    ]
