# Generated by Django 5.1.2 on 2025-01-06 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scolarapp', '0050_remove_user_education_level_user_education_levels'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='education_levels',
            new_name='education_level',
        ),
    ]
